media:
  - name: cms_test_images
    label: CMS Test Images
    input: _cms-test/uploads
    output: /cms-test/uploads
    extensions: [png, jpg, jpeg, webp]
    categories: [image]
    rename: safe

settings:
  content:
    merge: true

content:
  - name: journal
    label: Journal
    type: collection
    path: src/content/journal
    format: yaml-frontmatter
    subfolders: true

    operations:
      create: false
      rename: false
      delete: false

    view:
      fields: [title, lang, date, draft]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc

    fields:
      - name: title
        label: Title
        type: string

      - name: description
        label: Description
        type: text

      - name: date
        label: Date
        type: date
        readonly: true
        options:
          format: yyyy-MM-dd

      - name: draft
        label: Draft
        type: boolean

      - name: lang
        label: Language
        type: string
        readonly: true

      - name: translation
        label: Translation
        type: string
        readonly: true

      - name: body
        label: Body
        type: rich-text
        options:
          format: markdown
          media: cms_test_images
          switcher: true

  - name: cms_test_journal
    label: CMS Test Journal
    type: collection
    path: _cms-test/journal
    format: yaml-frontmatter
    subfolders: true

    operations:
      create: true
      rename: true
      delete: true

    filename:
      template: "{primary}.md"
      field: create

    view:
      fields: [title, lang, draft]
      primary: title

    fields:
      - name: title
        label: Title
        type: string

      - name: description
        label: Description
        type: text

      - name: draft
        label: Draft
        type: boolean

      - name: lang
        label: Language
        type: string

      - name: body
        label: Body
        type: rich-text
        options:
          format: markdown
          media: cms_test_images
          switcher: true